repos:
  - repo: local
    hooks:
    - id: mix-test
      name: 'elixir: mix test'
      entry: mix test
      language: system
      pass_filenames: false
      types: [elixir]
      verbose: true

    - id: mix-format
      name: 'elixir: mix format'
      entry: mix format --check-formatted
      language: system
      types: [elixir]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
