repos:
  - repo: local
    hooks:
    - id: mix-test
      name: 'elixir: mix test'
      entry: mix test
      language: system
      pass_filenames: false
      files: \.(ex|exs|heex)$
      verbose: true

    - id: mix-format
      name: 'elixir: mix format'
      entry: mix format --check-formatted
      language: system
      types: [elixir]

    - id: pnpm-test
      name: 'javascript: pnpm test'
      entry: bash -c 'cd assets && pnpm test'
      language: system
      pass_filenames: false
      files: \.(js|jsx|ts|tsx)$
      verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Sort imports
      - id: ruff
        args: ["check", "--select", "I", "--fix", "--config", "src = ['lib/atlas/ingest']"]
      # Run the formatter.
      - id: ruff-format
